### ISSUE TITLE
What's the effect of the translated name embeddings?

### ISSUE THREAD

**Issue by pigboomboom** [StephanieWyt/RDGCN#1]
A very nice work!

I replaced the initialization method with the random initialization and found that RDGCN failed to achieve promising performance, So I want to know what's the effect of the translated name embeddings?

Thanks!

**Comment by StephanieWyt** [comment]
Thanks for your interest in our work! 
Actually, entity names are very effective clues for entity alignment because the names of most aligned entities are similar in the DBP15K datasets. With the entity name initialization, our RDGCN model can further capture relation information and structural information to achieve better results,  compared to determining entity alignment by directly computing the similarities between entity names.

**Comment by LiuYuLOL** [comment]
Hi, thanks for the great work.

I also initialized the entity embedding randomly as there is no entity name in both KGs, and found the results are not so good. Just wondering how to deal with this case? (e.g. in both kgs, only IDs are available)

Besides, in the paper Table2, are these baselines using entity name embedding? and how about GCNs-random initial?

**Comment by StephanieWyt** [comment]
Hi,
Sorry for the late reply! Yes, without entity name initialization, our RDGCN might suffer a performance drop, since our model further captures relation information and structural information based on entity name semantics. If you have to use random initialization, you can try removing the highway gates from our model. In this way, the performance might be better.

In Table 2, all comparison baselines are randomly initialized. We can see that the GCN using random initialization can also achieve satisfactory results.

Best,
Yuting

**Comment by liu325967** [comment]
Hi, how did you get the initialization, and what operations did you perform on glove.840B.300d?
